version: '3.8'

services:
  backend:
    build: ./
    container_name: scd-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/vaultdb
      - DOCKER_ENV=true
    networks:
      - scd-network
    volumes:
      - ./backups:/app/backups
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: scd-mongodb
    networks:
      - scd-network
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  scd-network:
    driver: bridge
